apps/homepage/urls.py
from django.urls import path

from . import views


app_name = "homepage"

urlpatterns = [
    path("", views.HomeView.as_view(), name="home"),
    path("about/", views.AboutView.as_view(), name="about"),
]

apps/kakulator/api/v0/urls.py
from django.urls import path

from . import views


app_name = "kakulator"

urlpatterns = [path("", views.BasicKakulatorAPIView.as_view(), name="basic")]

apps/kakulator/urls.py
from django.urls import path

from . import views


app_name = "kakulator"

urlpatterns = [
    path("", views.BasicKakulatorView.as_view(), name="basic"),
]

conf/urls.py
from django.conf import settings
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path("", include("apps.homepage.urls", namespace="homepage")),
    path("api/", include("apps.api.urls", namespace="api")),
    path("kakulate/", include("apps.kakulator.urls", namespace="kakulator")),
    path("admin/", admin.site.urls),
]


if settings.DEBUG and "debug_toolbar" in settings.INSTALLED_APPS:
    import debug_toolbar

    urlpatterns += [
        path("__debug__/", include(debug_toolbar.urls)),
    ]

apps/kakulator/forms.py
from django import forms


class BasicKakulatorForm(forms.Form):
    query = forms.CharField(max_length=255)

apps/api/views.py
from django.views.generic import TemplateView


class DocsView(TemplateView):
    template_name = "api/docs.html"

apps/homepage/views.py
from django.views.generic import TemplateView


class HomeView(TemplateView):
    template_name = "homepage/home.html"


class AboutView(TemplateView):
    template_name = "homepage/about.html"

apps/kakulator/api/v0/views.py
from rest_framework import permissions
from rest_framework.response import Response
from rest_framework.views import APIView


from ...kakulate import kakulate


class BasicKakulatorAPIView(APIView):
    permission_classes = [permissions.AllowAny]

    def post(self, request, *args, **kwargs):
        if not (query := self.request.data.get("query")):
            return Response("Nothing to kakulate", status=400)

        kakulated_result = kakulate(query)

        # TODO: save kakulation to database

        return Response(
            {
                "query": query,
                "kakulated_result": kakulated_result,
            }
        )

apps/kakulator/views.py
from django.contrib import messages
from django.views.generic import TemplateView

from .exceptions import KakulationError
from .forms import BasicKakulatorForm
from .kakulate import kakulate


class BasicKakulatorView(TemplateView):
    template_name = "kakulator/basic.html"

    form = None

    def setup(self, request, *args, **kwargs):
        super().setup(request, *args, **kwargs)
        self.form = BasicKakulatorForm(request.GET or None)

    def get_context_data(self, **kwargs):
        ctx = super().get_context_data(**kwargs)
        ctx["kakulated_result"] = self.kakulate()
        return ctx

    def kakulate(self):
        if not (query := self.request.GET.get("query")):
            return None

        try:
            kakulated_result = kakulate(query)
        except KakulationError as e:
            messages.error(self.request, e)
            return None

        messages.success(self.request, "Success! Your request has been kakulated.")
        return kakulated_result

apps/api/templates/api/docs.html
{% extends "base.html" %}


{% block title %}
    {{ block.super }} | API
{% endblock %}

{% block content %}
    <section class="py-5 container">
        <h1 class="h2">
            {{ PROJECT_NAME }} API
        </h1>

        <p>
            Kakulator offers a RESTful API which allows you to kakulate your data remotely.
            Latest version of the API is located on <code>{{ PROJECT_URL }}/api/v0/</code>.
        </p>
        <p>
            The Kakulator API offers the following resources:
        </p>

        <div class="table-responsive">
        <table class="table table-hover">
            <thead>
            <tr>
                <th scope="col">Location</th>
                <th scope="col">Methods</th>
                <th scope="col">Details</th>
            </tr>
            </thead>
            <tbody>
            <tr>
                <th scope="row"><code>kakulate/</code></th>
                <td>
                    <span class="badge badge-success">POST</span>
                </td>
                <td>
                    {% with id="kakulate" %}
                        <button type="button" class="btn btn-sm btn-info my-0" data-toggle="modal" data-target="#{{ id }}">
                            Details
                        </button>
                        {% include "api/inc/modal/detail/kakulate.html" %}
                    {% endwith %}
                </td>
            </tr>
            </tbody>
        </table>

        </div>
    </section>
{% endblock content %}

apps/api/templates/api/inc/modal/detail/base.html
<div class="modal fade" id="{{ id }}" tabindex="-1" aria-labelledby="{{ id }}Label" aria-hidden="true">
    <div class="modal-dialog modal-dialog-centered modal-dialog-scrollable modal-lg">
        <div class="modal-content">
            <div class="modal-header">
                <h5 class="modal-title" id="exampleModalLabel">
                    {% block title %}{% endblock title %}
                </h5>
                <button type="button" class="close" data-dismiss="modal" aria-label="Close">
                    <span aria-hidden="true">&times;</span>
                </button>
            </div>
            <div class="modal-body">
                {% block content %}
                {% endblock content %}
            </div>
            <div class="modal-footer">
                <button type="button" class="btn btn-secondary" data-dismiss="modal">Close</button>
            </div>
        </div>
    </div>
</div>

apps/api/templates/api/inc/modal/detail/kakulate.html
{% extends "api/inc/modal/detail/base.html" %}

{% block title %}
    <code>kakulate/</code>
{% endblock %}

{% block content %}
    <p>Allowed methods: <span class="badge badge-success">POST</span></p>

    <h5>POST</h5>

    <div class="table-responsive">
        <table class="table table-bordered">
            <thead>
            <tr>
                <th scope="col">Parameter name</th>
                <th scope="col">Required</th>
                <th scope="col">Description</th>
            </tr>
            </thead>
            <tbody>
            <tr>
                <th scope="row">query</th>
                <td>yes</td>
                <td>Expression (string or integer) to kakulate.</td>
            </tr>
            </tbody>
        </table>
    </div>

    <h5>Example request</h5>
    <span class="text-muted">Through Linux CLI utility cURL:</span>
    <div class="card mb-3">
        <div class="card-body">
            <pre><code>curl -kX POST {{ PROJECT_URL }}{% url "api:v0:kakulator:basic" %} \
-H 'Accept: application/json' \
-H 'Content-Type: application/json' \
-d '{"query": "1+1"}'</code></pre>
        </div>
    </div>

    <h5>Example response</h5>
    <div class="card mb-3">
        <div class="card-body">
            <pre><code>{
    "query": "1+1",
    "kakulated_result": 42069
}</code></pre>
        </div>
    </div>
{% endblock content %}

apps/homepage/templates/homepage/about.html
{% extends "base.html" %}


{% block title %}
    {{ block.super }} | About
{% endblock %}

{% block content %}
    <section class="py-5 text-center container">
        <h1 class="mt-5">
            What we do
        </h1>
    </section>
{% endblock content %}

apps/homepage/templates/homepage/home.html
{% extends "base.html" %}


{% block title %}
    {{ block.super }} | Home
{% endblock %}

{% block content %}
    <section class="py-5 container">
        <div class="jumbotron">
            <h1 class="display-4">
                Welcome to Kakulator
            </h1>
            <p class="lead my-5">
                Kakulator is a web application, which uses cutting-edge mathematical software to satisfy all your kakulation needs.
            </p>
            <a class="btn btn-primary btn-lg" href="{% url "kakulator:basic" %}" role="button">
                Start Kakulating
            </a>
        </div>
    </section>
{% endblock content %}

apps/kakulator/templates/kakulator/basic.html
{% extends "base.html" %}

{% load crispy_forms_tags %}


{% block title %}
    {{ block.super }} | Kakulate
{% endblock %}

{% block content %}
    <section class="py-5 container">
        <h1 class="h2">
            Basic Kakulation
        </h1>

        <p>
            This is a basic demo of our cutting-edge kakulation software. Type your request into the 'Query' field,
            click the 'Kakulate' button and watch the magic happen!
        </p>
        <p class="font-italic">
            Note: Using advanced machine learning and quantum physics, the kakulation software has already
            processed your query before you even submitted it. As a result, when you click the 'Kakulate'
            button, you will receive your kakulated results instantly.
        </p>

        <form method="get">
            {% include "inc/messages.html" %}
            <div class="row align-items-end">
                <div class="col">
                    {{ view.form.query|as_crispy_field }}
                </div>
                <div class="col-auto pl-0">
                    <button type="submit" class="btn btn-block btn-primary mb-3">Kakulate</button>
                </div>
            </div>
        </form>
    </section>

    {% if kakulated_result %}
        <section class="py-5 container">
            <h2 class="h3">Kakulated result</h2>
            <p>This is the result of the kakulation:</p>

            <div class="card">
                <div class="card-body">
                    <h4>Query</h4>
                    {{ request.GET.query }}
                    <hr>
                    <h4>Result</h4>
                    {{ kakulated_result|linebreaksbr }}
                </div>
            </div>
        </section>

    {% endif %}
{% endblock content %}

templates/base.html
{% load static %}


<!doctype html>
<html lang="en">
<head>
    <!-- Required meta tags -->
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">

    <!-- Bootstrap CSS -->
    <link rel="stylesheet" href="{% static "libs/bootstrap/css/bootstrap.min.css" %}">

    <title>{% block title %}{{ PROJECT_NAME }}{% endblock title %}</title>
</head>
<body class="d-flex flex-column mb-0" style="min-height: 100vh">
<header class="navbar navbar-expand-md navbar-dark bg-dark">
    <nav class="container-xl flex-wrap flex-md-nowrap" aria-label="Main navigation">
        <a class="navbar-brand p-0 mr-2" href="{% url "homepage:home" %}" aria-label="Kakulator">
            Kakulator
        </a>
        <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#kkNavbar"
                aria-controls="kkNavbar" aria-expanded="false" aria-label="Toggle navigation">
            <svg xmlns="http://www.w3.org/2000/svg" width="24" height="24" class="" fill="currentColor"
                 viewBox="0 0 16 16">
                <path fill-rule="evenodd"
                      d="M2.5 11.5A.5.5 0 0 1 3 11h10a.5.5 0 0 1 0 1H3a.5.5 0 0 1-.5-.5zm0-4A.5.5 0 0 1 3 7h10a.5.5 0 0 1 0 1H3a.5.5 0 0 1-.5-.5zm0-4A.5.5 0 0 1 3 3h10a.5.5 0 0 1 0 1H3a.5.5 0 0 1-.5-.5z"></path>
            </svg>
        </button>

        <div class="navbar-collapse collapse" id="kkNavbar" style>
            <ul class="navbar-nav flex-row flex-wrap pt-2 py-md-0">
                <li class="nav-item col-6 col-md-auto">
                    <a href="{% url "homepage:home" %}" class="nav-link p-2">Home</a>
                </li>
                <li class="nav-item col-6 col-md-auto">
                    <a href="{% url "kakulator:basic" %}" class="nav-link p-2">Kakulate</a> {# TODO: kakulate url #}
                </li>
                <li class="nav-item col-6 col-md-auto">
                    <a href="{% url "api:docs" %}" class="nav-link p-2">API</a>
                </li>
                <li class="nav-item col-6 col-md-auto">
                    <a href="{% url "homepage:about" %}" class="nav-link p-2">About us</a>
                </li>
            </ul>

            <hr class="d-md-none bg-secondary">

            <ul class="navbar-nav flex-row flex-wrap ml-md-auto">
                <li class="nav-item col-6 col-md-auto">
                    <a class="nav-link p-2" href="https://github.com/pavlutom/kakulator" target="_blank" rel="noopener">
                        <svg xmlns="http://www.w3.org/2000/svg" width="16" height="16"
                             class="navbar-nav-svg d-inline-block align-text-top" viewBox="0 0 512 499.36" role="img">
                            <title>GitHub</title>
                            <path fill="currentColor" fill-rule="evenodd"
                                  d="M256 0C114.64 0 0 114.61 0 256c0 113.09 73.34 209 175.08 242.9 12.8 2.35 17.47-5.56 17.47-12.34 0-6.08-.22-22.18-.35-43.54-71.2 15.49-86.2-34.34-86.2-34.34-11.64-29.57-28.42-37.45-28.42-37.45-23.27-15.84 1.73-15.55 1.73-15.55 25.69 1.81 39.21 26.38 39.21 26.38 22.84 39.12 59.92 27.82 74.5 21.27 2.33-16.54 8.94-27.82 16.25-34.22-56.84-6.43-116.6-28.43-116.6-126.49 0-27.95 10-50.8 26.35-68.69-2.63-6.48-11.42-32.5 2.51-67.75 0 0 21.49-6.88 70.4 26.24a242.65 242.65 0 0 1 128.18 0c48.87-33.13 70.33-26.24 70.33-26.24 14 35.25 5.18 61.27 2.55 67.75 16.41 17.9 26.31 40.75 26.31 68.69 0 98.35-59.85 120-116.88 126.32 9.19 7.9 17.38 23.53 17.38 47.41 0 34.22-.31 61.83-.31 70.23 0 6.85 4.61 14.81 17.6 12.31C438.72 464.97 512 369.08 512 256.02 512 114.62 397.37 0 256 0z"></path>
                        </svg>
                        <small class="d-md-none ms-2">GitHub</small>
                    </a>
                </li>
            </ul>
        </div>
    </nav>
</header>

<main>
    {% block content %}
    {% endblock content %}
</main>

<footer class="border-top mt-auto">
    <div class="container-xl">
        <div class="d-flex justify-content-between py-3 text-secondary">
            <span>{{ PROJECT_NAME }}</span>
            <span>
                <a href="https://github.com/pavlutom/kakulator/issues/" target="_blank">Report an issue</a>
            </span>
            <span><b>Version:</b> {{ PROJECT_VERSION }}</span>
        </div>
    </div>
</footer>

<!-- Bootstrap -->
<script src="{% static "libs/jquery/jquery-3.5.1.min.js" %}"></script>
<script src="{% static "libs/popper/popper.min.js" %}"></script>
<script src="{% static "libs/bootstrap/js/bootstrap.min.js" %}"></script>
<script src="{% static "libs/bootstrap/js/bootstrap.bundle.min.js" %}"></script>

{% block scripts %}
{% endblock scripts %}

</body>
<footer>
</footer>
</html>

templates/inc/messages.html
{% if messages %}
    <div>
        {% for message in messages %}
            <div class="alert alert-{% if message.tags == "error" %}danger{% else %}{{ message.tags }}{% endif %} alert-dismissible fade show"
                 role="alert">
                {{ message }}
                <button type="button" class="close" data-dismiss="alert" aria-label="Close">
                    <span aria-hidden="true">&times;</span>
                </button>
            </div>
        {% endfor %}
    </div>
{% endif %}